### ISSUE TITLE
Can't add different type of geometry to layer

### ISSUE THREAD

**Issue by markov00** [ubilabs/google-maps-api-threejs-layer#6]
Hi, I'm trying to add a plane geometry and a circle geometry into the layer but without success. The only geometry I can add are a BoxGeometry and a SphereGeometry. Could you please show me what I'm doing wrong?
If I add these objects on a simple ThreeJS scene I can see correctly them, but here I can see only the Box.

    var container = document.getElementById('map');

    var map = new google.maps.Map(container, {
        zoom: 3,
        mapTypeControl: false,
        center: new google.maps.LatLng(0,0),
        mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    new ThreejsLayer({
            map: map
        },
        function (layer) {

            var location = new google.maps.LatLng(0, 0),
                vertex = layer.fromLatLngToVertex(location);

            var geometry = new THREE.BoxGeometry(10, 10, 1);
            var material = new THREE.MeshBasicMaterial({color: 0x00ff00});
            var cube = new THREE.Mesh(geometry, material);

            cube.position.x = vertex.x;
            cube.position.y = vertex.y;

            layer.add(cube); //this is shown

            location = new google.maps.LatLng(20, 20);
            vertex = layer.fromLatLngToVertex(location);

            geometry = new THREE.PlaneGeometry(10, 10);
            material = new THREE.MeshBasicMaterial({color: 0xFF0000});
            var plane = new THREE.Mesh(geometry, material);

            plane.position.x = vertex.x;
            plane.position.y = vertex.y;

            layer.add(plane); //this is not shown

        });

**Comment by markov00** [comment]
I think I've found the problem. It's because you are using the orthographic camera with inverted top,bottom and this means that everything is inverted vertically and for planar geometry like PlaneGeometry, CircleGeometry etc you need to specify a double side material like:

    var material = new THREE.MeshBasicMaterial({
        color: 0x00ff00,
        side: THREE.DoubleSide
    });

Do you think it's the only way to use the orthographic camera?

**Comment by korczis** [comment]
Any news?

**Comment by korczis** [comment]
Any news?

**Comment by korczis** [comment]
Any news?
