### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by geraldstanje** [ubilabs/google-maps-api-threejs-layer#9]
Hi,

is there a way to add show a info window (google.maps.InfoWindow) on the map if you click on placed point (lat/long)?

Thanks

**Comment by korczis** [comment]
H @geraldstanje , this is little bit tricky. I have all points which are part of layer in using https://github.com/mourner/rbush  so when user click I search in rbush for closest point and display infowindow.

**Comment by aemkei** [comment]
Thanks @korczis: IMO using a kd-tree is the best option here. You might want to check out this library, too: https://github.com/ubilabs/kd-tree-javascript

**Comment by korczis** [comment]
@aemkei I am aware of existence of your Kd tree library but I am not sure how actively is developed and/or maintained.

PS: What are the further plans with this project? I found few bugs and have few feature requests but I am not sure if I should report them.
